
name: check jolts data 

on: 
  
  schedule:
    - cron: "10 14 * * 1,2,3,4,5"  # check Monday through Friday at 10:10 am 
  #   # note github actions runs on UTC.

jobs:
  import-data:
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.BLS_PUSH_ACCESS}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID}}
    permissions: 
      contents: write
      
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
           any::aws.s3
           any::blsR
           any::readr
           any::tidyverse
           
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BLS_PUSH_ACCESS}}
      
      - name: Create and populate .Renviron file
        run: |
         echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID}}    >> ~/.Renviron
         echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}} >> ~/.Renviron
         
         
      - name: Import data
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID}}
          
        run: 
          Rscript scripts/20231010_check_bls_data.R

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
     
         
       

